build(betas): fastlane + ci setup (#57)
* Faslane setup

* fastfile

* remove android and eigen specific stuff for now

* update keynames and metadata for codesigning

* fix plist paths

* fix paths and scheme name in build action

* call release config, Store to allow different code signing settings

* add ipad icons, standardize icon names

* working beta, require fullscreen for now

* add notify lane, update version lane

* update copyright date

* add orbs, clean slate circle config

* copy over jobs, commands and workflows we need

* reset all cache numbers

* add manifest generation file

* add secrets script, execute permissions

* add aws setup script

* fix aws script name

* add ci env setup script

* add danger as dev dep

* add dangerfile from eigen

* remove strictness migration check

* add secrets baseline and generation script

* add type-check command, comment out step for now

* add eslint prettier plugin, comment out lint step for now

* add jest-junit dev dep

* remove js bundling, unnecessary?

* add node to tool-versions, update lockfile

* update node version used by ci

* update node executors in ci

* use a supported node version

* update download fonts script name

* add required gems for ci

* add android and ios build and related scripts

* try specifying bundle install path

* try specifying bundle install path for pod install step

* add bundle config

* comment out android workflow for now

* add deploy-ios script

* Revert "try specifying bundle install path for pod install step"

This reverts commit 972b1bf1de653dc2a908f70ff6cffacbb18061dc.

* remove unnecessary path specification

* specify ruby version

* install specific ruby version before gems

* fix ruby install step

* use the macos orb for ruby switch

* please just use the same ruby across steps

* use a supported ruby version on macos machine

* delete extra Gemfile and lockfile

* add missing ci-ios script

* add missing test ios scripts

* get rid of circle specific danger

* add beta distribution scripts

* just use same env for ci

* load shared env in fastfile and podfile

* add circle setup call to fastfile

* maybe we need relay here?

* try a lower xcode version for now

* really try a lower xcode version for now

* use an available ruby

* try the bundle script from create react app

* try using a lower node version

* fix app approval description

* use latest Xcode again

* remove unnecessary ruby switch and orb

* remove unnecessary yarn relay

* add other fastlane tasks

* update horizon id

* node versions :(

* pr review, newlines

* missed a spot

* longer timeout for native tests

Co-authored-by: brainbicycle <brian.beckerle@artsymail.com>
Co-authored-by: Brian Beckerle <49686530+brainbicycle@users.noreply.github.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,26 +1,502 @@
-# Use the latest 2.1 version of CircleCI pipeline process engine.
-# See: https://circleci.com/docs/2.0/configuration-reference
 version: 2.1
 
-# Define a job to be invoked later in a workflow.
-# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
+orbs:
+  node: circleci/node@5.0.2
+  queue: eddiewebb/queue@1.7.0
+  horizon: artsy/release@0.0.1
+
+commands:
+  await-previous-builds:
+    parameters:
+      branch:
+        description: The branch to wait on
+        type: string
+    steps:
+      - queue/until_front_of_line:
+          time: "30" # how long a queue will wait until the job exits
+          only-on-branch: <<parameters.branch>> # restrict queueing to a specific branch (default *)
+  install-node:
+    steps:
+      - run:
+          name: Install Node 16 (Required for Yarn)
+          command: |
+            set +e
+            touch $BASH_ENV
+            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
+            echo "HOMEBREW_NO_AUTO_UPDATE=1" >> $BASH_ENV
+            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
+            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
+            echo 'nvm install v16.10.0' >> $BASH_ENV
+            echo 'nvm alias default v16.10.0' >> $BASH_ENV
+            sudo mkdir ~/.config
+            sudo chown -R $USER:$GROUP ~/.config
+  generate-checksums:
+    steps:
+      - run:
+          name: "Generate initial checksum manifests"
+          command: |
+            mkdir .manifests
+            scripts/generate-manifest.js .manifests/node_modules '^yarn\.lock$' '^patches/' '^package\.json$'
+            scripts/generate-manifest.js .manifests/js_transform '^\.manifests/node_modules' '^babel\.config\.js' '^relay\.config\.js' '^jest\.config\.js'
+            scripts/generate-manifest.js .manifests/js_bundle '^\.manifests/js_transform' '^data/' '^index\.ios\.js' '^src/(?!.*(__mocks__|__fixtures__))'
+            scripts/generate-manifest.js .manifests/cocoapods '^Podfile' '^Gemfile'
+            scripts/generate-manifest.js .manifests/native_code '^\.manifests/node_modules' '^Podfile' '^Gemfile' '^dist/' '^Artsy' '^patches/react-native' '^\.env\.example'
+            scripts/generate-manifest.js .manifests/android_native '^\.manifests/node_modules' '^android/' '^patches/react-native' '^\.env\.example'
+  setup-env-file:
+    steps:
+      - run:
+          name: "Set up .env file"
+          command: scripts/setup-env-for-ci
+  setup-awscli:
+    steps:
+      - run:
+          name: "Set up aws cli not installed"
+          command: scripts/setup-awscli
+  install-node-modules:
+    steps:
+      - restore_cache:
+          keys:
+            - v1-node_modules-{{ checksum ".manifests/node_modules" }}-{{ arch }}
+      - run:
+          name: Install node modules
+          command: ls node_modules || yarn install
+      - save_cache:
+          key: v1-node_modules-{{ checksum ".manifests/node_modules" }}-{{ arch }}
+          paths:
+            - node_modules
+  run-relay-compiler:
+    steps:
+      - run:
+          name: Run Relay compiler
+          command: yarn relay
+  test-js:
+    steps:
+      - restore_cache:
+          keys:
+            - v1-jest-{{ .Branch }}
+      # - run:
+      #     name: Run TypeScript check
+      #     command: yarn type-check
+      # - run:
+      #     name: Run TSLint check
+      #     command: yarn lint
+      - run:
+          name: Run jest tests
+          command: yarn jest --ci --forceExit --runInBand --reporters=default --reporters=jest-junit
+          environment:
+            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
+      - save_cache:
+          key: v1-jest-{{ .Branch }}
+          paths:
+            - .jest
+  install-gems:
+    steps:
+      - restore_cache:
+          keys:
+            - v1-gems-{{ checksum "Gemfile.lock" }}-{{ arch }}
+      - run:
+          name: Bundle install
+          command: bundle check || bundle install
+          environment:
+            BUNDLE_JOBS: 4
+            BUNDLE_RETRY: 3
+      - save_cache:
+          key: v1-gems-{{ checksum "Gemfile.lock" }}-{{ arch }}
+          paths:
+            - .vendor
+  install-cocoapods:
+    steps:
+      - restore_cache:
+          keys:
+            - v1-pods-{{ checksum ".manifests/cocoapods" }}
+      - run:
+          name: Install Pods
+          command: cd ios; bundle exec pod check --ignore-dev-pods || bundle exec pod install; cd ..;
+      - save_cache:
+          key: v1-pods-{{ checksum ".manifests/cocoapods" }}
+          paths:
+            - ios/Pods
+            # this changes after pod install because we don't install dev tools on CI
+            # so we save it to the cache to avoid comparison errors with Pods/Manifest.lock
+            - ios/Podfile.lock
+  build-app-ios:
+    steps:
+      - restore_cache:
+          keys:
+            - v1-app_build_ios-{{ checksum ".manifests/app_build" }}
+      - run:
+          name: Download fonts from s3
+          command: ./scripts/download-fonts
+      - run:
+          name: Build App
+          command: ./scripts/ci-ios
+      - save_cache:
+          key: v1-app_build_ios-{{ checksum ".manifests/app_build" }}
+          paths:
+            - derived_data
+            - node_modules/react-native-config
+  prep-android-env:
+    steps:
+      - attach_workspace:
+          at: ../workspace
+      - run:
+          name: Clear project dir
+          command: |
+            rm -rf /Users/distiller/project
+      - checkout
+      - attach_workspace:
+          at: .
+      - install-node
+      - setup-awscli
+      - setup-env-file
+      - restore_cache:
+          keys:
+            - v1-test-success-{{ checksum "../workspace/.manifests/android_native" }}
+      - run:
+          name: Quit early if possible
+          command: |
+            if test $CIRCLE_BRANCH != beta-android && ls build-success.log
+            then
+              circleci step halt
+            fi
+      - install-node-modules
+      - run-relay-compiler
+      - install-gems
+  build-app-android:
+    steps:
+      - restore_cache:
+          keys:
+            - v1-app_build_android-{{ checksum ".manifests/app_build" }}
+      - run:
+          name: Download fonts from s3
+          command: ./scripts/download-fonts
+      - run:
+          name: Build App
+          command: ./scripts/ci-android
+      - save_cache:
+          key: v1-app_build_android-{{ checksum ".manifests/app_build" }}
+          paths:
+            - android/build
+            - android/app/build
+            - node_modules/react-native-config
+
 jobs:
-  say-hello:
-    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
-    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
+  detect-secrets:
     docker:
-      - image: cimg/base:stable
-    # Add steps to the job
-    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
+      - image: artsy/detect-secrets:1.2.0
+    working_directory: /usr/src/app
     steps:
       - checkout
-      - run:
-          name: "Say hello"
-          command: "echo Hello, World!"
+      - run: ./scripts/secrets-check-all
 
-# Invoke jobs via workflows
-# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
+  deploy-nightly-beta:
+    environment:
+      BUNDLE_PATH: .vendor # path to install gems and use for caching
+    macos:
+      xcode: 13.4.1
+    steps:
+      - checkout
+      - install-node
+      - run:
+          name: Deploy beta
+          command: ./scripts/deploy-both
+
+  check-pr:
+    executor:
+      name: node/default
+      tag: "16.10.0"
+    steps:
+      - checkout
+      - generate-checksums
+      - install-node-modules
+      - run-relay-compiler
+      - run:
+          name: Danger
+          command: yarn danger ci --verbose
+
+  check-if-app-has-been-approved-for-release:
+    environment:
+      BUNDLE_PATH: .vendor # path to install gems and use for caching
+
+    macos:
+      xcode: 13.4.1
+
+    steps:
+      - checkout
+      - generate-checksums
+      - install-gems
+      - run:
+          name: Check if app has been approved for release
+          command: ./scripts/check-if-app-has-been-approved-for-release.sh
+
+  build-test-js:
+    executor:
+      name: node/default
+      tag: "16.10.0"
+    resource_class: large
+    steps:
+      - checkout
+      - generate-checksums
+      - setup-awscli
+      - setup-env-file
+      - install-node-modules
+      - run-relay-compiler
+      - run:
+          name: Check generated folder
+          command: |
+            if test "$(git diff -- src/__generated__)"
+            then
+              echo 'You forgot to run `yarn relay` before comitting'
+              exit 1
+            fi
+      - test-js
+      - run:
+          name: Generate app_build manifest
+          command: ./scripts/generate-manifest.js .manifests/app_build '^\./manifests/native_code' '^dist/'
+      - store_artifacts:
+          path: .manifests
+      - store_test_results:
+          path: ./reports/junit/
+      - persist_to_workspace:
+          root: .
+          paths:
+            - .manifests
+            - dist
+
+  build-test-app-ios:
+    environment:
+      BUNDLE_PATH: .vendor # path to install gems and use for caching
+
+    macos:
+      xcode: 13.4.1
+
+    steps:
+      - attach_workspace:
+          at: ../workspace
+      - restore_cache:
+          keys:
+            - v1-test-success-{{ checksum "../workspace/.manifests/native_code" }}
+      # we can quit the macos build early if there were no native code changes
+      # and we're not on the beta branch
+      - run:
+          name: Quit early if possible
+          command: |
+            if test $CIRCLE_BRANCH != beta-ios && ls xcode_test_raw.log
+            then
+              circleci step halt
+            fi
+      - run:
+          name: Quit early if Draft PR
+          command: |
+            if $(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/artsy/eigen/pulls/${CIRCLE_PULL_REQUEST##*/} | jq ".draft")
+            then
+              circleci step halt
+            fi
+      - run:
+          name: Clear project dir
+          command: |
+            rm -rf /Users/distiller/project
+      - checkout
+      - attach_workspace:
+          at: .
+      - install-node
+      - setup-awscli
+      - setup-env-file
+      - install-node-modules
+      - install-gems
+      - install-cocoapods
+      - run-relay-compiler
+      - build-app-ios
+      - run:
+          name: Run tests if native code has changed
+          no_output_timeout: 20m
+          command: ls xcode_test_raw.log || ./scripts/ci-test-ios
+      - save_cache:
+          key: v1-test-success-{{ checksum ".manifests/native_code" }}
+          paths:
+            - xcode_test_raw.log
+      - store_artifacts:
+          path: xcode_build_raw.log
+          prefix: build
+      - store_artifacts:
+          path: xcode_test_raw.log
+          prefix: tests
+      - await-previous-builds:
+          branch: beta-ios
+      - run:
+          name: Deploy if beta
+          no_output_timeout: 20m
+          command: ./scripts/deploy-if-beta-branch-ios
+
+  build-test-app-android:
+    environment:
+      BUNDLE_PATH: .vendor # path to install gems and use for caching
+    docker:
+      - image: circleci/android:api-29-node
+    resource_class: large
+    steps:
+      - prep-android-env
+      - await-previous-builds:
+          branch: beta-android
+      - build-app-android
+      - run:
+          name: Save success file
+          command: echo yes > 'build-success.log'
+
+      - store_artifacts:
+          path: android/app/build/reports
+          prefix: android-build
+
+      - save_cache:
+          key: v1-test-success-{{ checksum "../workspace/.manifests/android_native" }}
+          paths:
+            - build-success.log
+      - run:
+          name: Deploy if beta - play store and firebase
+          command: ./scripts/deploy-if-beta-branch-android BOTH
+
+  promote-beta-to-app-store:
+    environment:
+      BUNDLE_PATH: .vendor # path to install gems and use for caching
+    macos:
+      xcode: 13.4.1
+    steps:
+      - checkout
+      - install-gems
+      - await-previous-builds:
+          branch: app_store_submission
+      - run:
+          name: Promote if app_store_submission
+          command: ./scripts/promote-if-appstore-submission-branch
+
+  promote-beta-to-play-store:
+    environment:
+      BUNDLE_PATH: .vendor # path to install gems and use for caching
+
+    docker:
+      - image: circleci/android:api-29-node
+
+    steps:
+      - checkout
+      - install-gems
+      - await-previous-builds:
+          branch: play_store_submission
+      - run:
+          name: Setup
+          command: ./scripts/setup-distribute
+      - run:
+          name: Promote if play_store_submission
+          command: ./scripts/promote-if-playstore-submission-branch
+
+  release-ios-app:
+    environment:
+      BUNDLE_PATH: .vendor # path to install gems and use for caching
+    macos:
+      xcode: 13.4.1
+    steps:
+      - checkout
+      - install-gems
+      - run:
+          name: Release app version
+          command: ./scripts/release-ios-app-branch
+
 workflows:
-  say-hello-workflow:
+  version: 2
+  nightly:
+    triggers:
+      - schedule:
+          cron: "0 6 * * *"
+          filters:
+            branches:
+              only:
+                - main
     jobs:
-      - say-hello
+      - deploy-nightly-beta
+
+  check-if-app-has-been-approved-for-release-workflow:
+    triggers:
+      - schedule:
+          cron: "0 4 * * 1-5"
+          filters:
+            branches:
+              only:
+                - main
+    jobs:
+      - check-if-app-has-been-approved-for-release
+
+  release-ios-app-workflow:
+    jobs:
+      - release-ios-app:
+          filters:
+            branches:
+              only:
+                - release-ios-app
+  promote:
+    jobs:
+      - promote-beta-to-app-store:
+          filters:
+            branches:
+              only:
+                - app_store_submission
+      - promote-beta-to-play-store:
+          filters:
+            branches:
+              only:
+                - play_store_submission
+
+  test-build-deploy:
+    jobs:
+      - detect-secrets:
+          filters:
+            branches:
+              ignore:
+                - main
+                - release
+                - staging
+      - check-pr:
+          filters:
+            branches:
+              ignore:
+                - main
+                - beta-ios
+                - beta-android
+                - app_store_submission
+                - play_store_submission
+                - update-changelog
+      - build-test-js:
+          filters:
+            branches:
+              ignore:
+                - app_store_submission
+                - play_store_submission
+                - update-changelog
+      - horizon/block:
+          context: horizon
+          project_id: 43
+          filters:
+            branches:
+              only:
+                - beta-ios
+                - beta-android
+      - build-test-app-ios:
+          filters:
+            branches:
+              ignore:
+                - app_store_submission
+                - play_store_submission
+                - beta-android
+                - update-changelog
+          requires:
+            - build-test-js
+            - horizon/block
+      # - build-test-app-android:
+      #     filters:
+      #       branches:
+      #         ignore:
+      #           - app_store_submission
+      #           - play_store_submission
+      #           - beta-ios
+      #           - update-changelog
+      #     requires:
+      #       - build-test-js
+      #       - horizon/block
